[package]
name = "bookish-telegram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
axum = "0.6.0"
tokio = {version="1.22.0", features=["macros", "rt-multi-thread"]}
