steps:
  - name: rust:1.65
    script: |
      rustup update
      rustup component add clippy
      cargo clippy

  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=gcr.io/$PROJECT_ID/image
