steps:
  - name: rust:1.65
    script: |
      rustup update
      rustup component add clippy
      cargo clippy

  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/bookish-telegram/registry/example:latest
      - --destination=asia-northeast1-docker.pkg.dev/bookish-telegram/registry/example:$COMMIT_SHA
